services:
  app:
    container_name: web-toolkit
    image: ghcr.io/coccoto/web-toolkit:latest
    restart: unless-stopped
    ports:
      - "18010:18010"
    env_file:
      - ./.env
    networks:
      - web-toolkit-network

networks:
  web-toolkit-network:
    name: web-toolkit-network
    external: true
