services:
  server:
    container_name: web-toolkit
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${NEXT_PUBLIC_PORT}:${NEXT_PUBLIC_PORT}"
    volumes:
      - ./logs:/app/logs
    env_file:
      - .env
